/* Antikythera Shipwreck — searchable gallery dataset.
   Compiled from official museum and project sources (September 2026).
   Catalogue numbers: National Archaeological Museum (NAM), Athens.
   X / Xρ prefixes follow the museum's metal (X) and precious-metal (Xρ = Χρυsoί) series. */

const PROV = {
  odysseusEphebe: "http://odysseus.culture.gr/h/4/eh430.jsp?obj_id=4508",
  odysseusPhilosopher: "http://odysseus.culture.gr/h/4/eh430.jsp?obj_id=5564",
  odysseusMechanism: "http://odysseus.culture.gr/h/4/eh430.jsp?obj_id=5582",
  namExhibition: "https://www.namuseum.gr/en/temporary_exhibition/to-nayagio-ton-antikythiron-to-ploio-oi-thisayroi-o-michanismos/",
  namHellenistic: "https://www.namuseum.gr/en/collection/ellinistiki-periodos-3/",
  booklet: "http://mattgoodmanuk.com/links/AntikytheraMechanism_files/Booklet_TheAntikytheraExhibition2012.pdf",
  rtaGlass: "https://antikythera.org.gr/artifacts/glassware/",
  rtaAmphorae: "https://antikythera.org.gr/artifacts/amphorae/",
  rtaLamps: "https://antikythera.org.gr/artifacts/lamps/",
  rtaMechanism: "https://antikythera.org.gr/artifacts/antikythera-mechanism/",
  rta2017: "https://antikythera.org.gr/2017/10/04/2288/",
  nyuAll: "https://archive.nyu.edu/handle/2451/44191",
  nyuDG: "https://archive.nyu.edu/handle/2451/44441",
  nyuSvoronos: "https://archive.nyu.edu/handle/2451/59968",
  whoi2016: "https://www.whoi.edu/press-room/news-release/artifacts-discovered-on-return-expedition-to-antikythera-shipwreck/",
  sciNews2014: "https://www.sci.news/archaeology/science-antikythera-shipwreck-02201.html",
  wikiWreck: "https://en.wikipedia.org/wiki/Antikythera_wreck",
  wikiMechanism: "https://en.wikipedia.org/wiki/Antikythera_mechanism",
  wikiHeracles: "https://en.wikipedia.org/wiki/Heracles_of_Antikythera",
  cambridge2025: "https://www.cambridge.org/core/blog/2025/10/08/the-statues-from-the-antikythera-shipwreck-125-years-later/",
  sissaOverview: "https://pos.sissa.it/170/006/pdf",
  agEphebe: "https://ancient-greece.org/antikythera-shipwreck-12/",
  agPhilosopher: "https://ancient-greece.org/antikythera-shipwreck-14/",
  agBoxerArm: "https://ancient-greece.org/antikythera-shipwreck-16/",
  agStatuette: "https://ancient-greece.org/antikythera-shipwreck-18/",
  agBoy: "https://ancient-greece.org/antikythera-shipwreck-19/",
  agJewellery: "https://ancient-greece.org/antikythera-shipwreck-7/",
  agBronzeVessels: "https://ancient-greece.org/antikythera-shipwreck-8/",
  agPottery: "https://ancient-greece.org/antikythera-shipwreck-6/",
  agShipParts: "https://ancient-greece.org/antikythera-shipwreck-2/",
  agHull: "https://ancient-greece.org/antikythera-shipwreck-1/",
  agTiles: "https://ancient-greece.org/antikythera-shipwreck-3/",
  agUtensils: "https://ancient-greece.org/antikythera-shipwreck-5/",
  agFragments: "https://ancient-greece.org/antikythera-shipwreck-15/",
  arHeracles: "https://ancientrome.ru/art/artworken/img.htm?id=6139",
  arEphebe: "https://ancientrome.ru/art/artworken/img.htm?id=6145",
  arPhilosopher: "https://ancientrome.ru/art/artworken/img.htm?id=6148",
};

const ARTIFACTS = [
  /* ============ STATUARY — BRONZE ============ */
  {
    id: "ephebe", cat: "statuary", group: "Bronze statuary",
    name: "The Youth of Antikythera (“Ephebe”)",
    material: "bronze", matDetail: "Bronze (copper alloy)",
    campaign: "1900-01", date: "c. 340–330 BC",
    inv: "NAM X 13396",
    imgKind: "commons", imgFile: "Antikythera Ephebe, bronze, 70–60 BC, NAMA X 13396, 190893.jpg",
    imgAlt: "Bronze statue of a youth standing with one arm raised, on display in the National Archaeological Museum, Athens",
    imgStatus: "high-res",
    prov: [
      { label: "ODYSSEUS (Hellenic Ministry of Culture) record", url: PROV.odysseusEphebe },
      { label: "NAM exhibition “The Antikythera Shipwreck”", url: PROV.namExhibition },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Perhaps the most celebrated find: a life-size bronze youth, restored in 1953. The museum label suggests Perseus (with Medusa’s head) or Paris (with the apple of Strife), attributed speculatively to the Sikyonian sculptor Euphranor. Some Wikimedia Commons files carry a later dating of 70–60 BC; the museum dates it around 340–330 BC. Displayed in Room 28 (Vases and Minor Arts).",
  },
  {
    id: "philosopher", cat: "statuary", group: "Bronze statuary",
    name: "The Philosopher of Antikythera",
    material: "bronze", matDetail: "Bronze (copper alloy)",
    campaign: "1900-01", date: "c. 240–230 BC",
    inv: "NAM X 13400 (with X 15088, X 15090, X 15091, X 15105, X 15108, X 18932)",
    imgKind: "commons", imgFile: "Antikythera philosopher.JPG",
    imgAlt: "Bronze portrait head of a bearded philosopher with deeply modelled features",
    imgStatus: "moderate",
    prov: [
      { label: "ODYSSEUS (Hellenic Ministry of Culture) record", url: PROV.odysseusPhilosopher },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "NAM Hellenistic collection", url: PROV.namHellenistic },
    ],
    notes: "Portrait head and associated fragments (hands, sandalled feet, himation fragments) of a life-size bronze of a Cynic philosopher, tentatively identified as Bion of Borysthenes or Philitas of Cos. Recovered 1900–01; displayed in Room 30 (Bronzes).",
  },
  {
    id: "statuette-youth", cat: "statuary", group: "Bronze statuary",
    name: "Bronze statuette of a youth",
    material: "bronze", matDetail: "Bronze (copper alloy)",
    campaign: "1900-01", date: "Late 2nd c. BC",
    inv: "NAM X 18957",
    imgKind: "local", imgSrc: "assets/external/statuette-youth-18957.jpg",
    imgAlt: "Ancient bronze statuette of a standing nude youth in contrapposto, with dark marine patina, displayed on a modern mount",
    imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-18.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agStatuette },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-18.jpeg" },
    ],
    notes: "One of five classicizing bronze statuettes in the cargo, modelled on Praxitelean types. Scholarly overviews note that a right arm belonging to a bronze statuette was among the finds of the 1976 expedition. Photograph: ancient-greece.org, CC BY-NC-ND 4.0.",
  },
  {
    id: "boxer-arm", cat: "statuary", group: "Bronze statuary",
    name: "Left arm of a boxer statue, with leather thongs",
    material: "bronze", matDetail: "Bronze with preserved leather wraps",
    campaign: "1900-01", date: "Late 2nd – early 1st c. BC",
    inv: null, invNote: "Catalogue number not published in the consulted sources",
    imgKind: "commons", imgFile: "Leather wraps, Ancient Greece, boxing gloves.png",
    imgAlt: "Bronze forearm of a statue wrapped with crossed leather thongs, ancient boxing protection",
    imgStatus: "moderate",
    prov: [
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agBoxerArm },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Larger-than-life left forearm with the thumb, wrist and lower arm tightly crossed by leather thongs — the protective wrapping of a victorious athlete. The piece probably belonged to a statue displayed in a palaestra or gymnasion.",
  },
  {
    id: "boxer-statuette", cat: "statuary", group: "Bronze statuary",
    name: "Bronze statuette of a boxer",
    material: "bronze", matDetail: "Bronze (copper alloy)",
    campaign: "1900-01", date: "c. 100 BC (after Classical models)",
    inv: null, invNote: "Catalogue number not published in the consulted sources",
    imgKind: "commons", imgFile: "Statua di pugilatore, dal relitto di antikythera, 100 ac ca. da modelli classici, 01.jpg",
    imgAlt: "Small bronze statuette of a boxer in classical pose",
    imgStatus: "high-res",
    prov: [
      { label: "Wikimedia Commons file page", url: "https://commons.wikimedia.org/wiki/File:Statua_di_pugilatore,_dal_relitto_di_antikythera,_100_ac_ca._da_modelli_classici,_01.jpg" },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Classicizing statuette of a boxer from the wreck, photographed at the 2012 NAM exhibition. Identification rests on the photographer’s caption; a formal museum catalogue number was not located in the official sources consulted.",
  },
  {
    id: "bronze-lyre", cat: "statuary", group: "Bronze statuary",
    name: "Bronze lyre (from a statuette of Apollo or Eros)",
    material: "bronze", matDetail: "Bronze (copper alloy)",
    campaign: "1900-01", date: "Hellenistic",
    inv: null, invNote: "Catalogue number not published in the consulted sources",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "Scholarly overview (Sissa PoS, 2016)", url: PROV.sissaOverview },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "A bronze lyre belonging to a small statuette — evidence for musical-iconography sculpture in the cargo. Bone fragments of musical instruments (aulos pipes) were also recovered.",
  },
  {
    id: "bronze-feet", cat: "statuary", group: "Bronze statuary",
    name: "Feet from bronze statues",
    material: "bronze", matDetail: "Bronze (copper alloy)",
    campaign: "1900-01", date: "3rd – 2nd c. BC",
    inv: "NAM X 15093; NAM X 15115",
    imgKind: "local", imgSrc: "assets/external/bronze-arms-feet.jpg",
    imgAlt: "Bronze statue fragments: arms above and sandalled feet below, with heavy marine patina", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-15.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-15.jpeg" },
    ],
    notes: "A left foot from a statue (X 15093, 2nd c. BC ?) and the right foot of a male statue wearing a sandal (X 15115, 225–200 BC) — workshop-cast replacements, illustrating the serial production of bronze statue parts. The exhibition photograph also shows arms from bronze statues. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },

  /* ============ STATUARY — MARBLE ============ */
  {
    id: "heracles", cat: "statuary", group: "Marble statuary",
    name: "Heracles of Antikythera (Farnese type)",
    material: "marble", matDetail: "Parian marble",
    campaign: "1900-01", date: "Late Hellenistic copy after Lysippos (original c. 320 BC)",
    inv: "NAM 5742",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.arHeracles,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "Wikipedia — Heracles of Antikythera", url: PROV.wikiHeracles },
      { label: "Gallery of Ancient Art photograph (ancientrome.ru)", url: PROV.arHeracles },
    ],
    notes: "Over-life-size marble Heracles, a late Hellenistic copy of the type created by Lysippos of Sikyon. The body was recovered in 1901; a hand was found in 2016, and the head — crowned with a wreath of vine leaves — was recovered in the 2022 season (later campaigns, beyond the 2012–14 scope of this report).",
  },
  {
    id: "zeus", cat: "statuary", group: "Marble statuary",
    name: "Seated Zeus",
    material: "marble", matDetail: "Marble",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM 5743",
    imgKind: "commons", imgFile: "Zeus of Antikythera.jpg",
    imgAlt: "Fragmentary marble statue of a seated Zeus from the Antikythera shipwreck",
    imgStatus: "moderate",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "Wikimedia Commons file page", url: "https://commons.wikimedia.org/wiki/File:Zeus_of_Antikythera.jpg" },
    ],
    notes: "Seated, over-life-size figure; some scholarship alternatively identifies it as Poseidon. One of the monumental marbles that made the cargo famous.",
  },
  {
    id: "odysseus", cat: "statuary", group: "Marble statuary",
    name: "Odysseus (?)",
    material: "marble", matDetail: "Marble",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM 5745",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Bearded figure published in the 2012 exhibition catalogue under this identification; the attribution to Odysseus (rather than, say, a philosopher type) remains interpretive. No open-licence photograph was located.",
  },
  {
    id: "achilles", cat: "statuary", group: "Marble statuary",
    name: "Achilles (?)",
    material: "marble", matDetail: "Marble",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM 5746",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Published in the 2012 exhibition catalogue with a queried identification. No open-licence photograph was located.",
  },
  {
    id: "hermes", cat: "statuary", group: "Marble statuary",
    name: "Head of Hermes (after the “Richelieu” type)",
    material: "marble", matDetail: "Marble",
    campaign: "1900-01", date: "Early 1st c. BC",
    inv: "NAM 2774",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Head from a statue of Hermes copying a Late Classical prototype. No open-licence photograph was located.",
  },
  {
    id: "apollo", cat: "statuary", group: "Marble statuary",
    name: "Apollo with tripod",
    material: "marble", matDetail: "Marble",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM 15487",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Cult-image type of Apollo holding a tripod, listed in the 2012 exhibition catalogue. No open-licence photograph was located.",
  },
  {
    id: "youth-5744", cat: "statuary", group: "Marble statuary",
    name: "Statue of a youth (athlete or dancer)",
    material: "marble", matDetail: "Parian marble",
    campaign: "1900-01", date: "Early 1st c. BC",
    inv: "NAM 5744",
    imgKind: "commons", imgFile: "Statue of a youth-Antikythera wreck-NAMA 5744.jpg",
    imgAlt: "Marble statue of a youth in twisting pose from the Antikythera shipwreck",
    imgStatus: "moderate",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "Wikimedia Commons file page", url: "https://commons.wikimedia.org/wiki/File:Statue_of_a_youth-Antikythera_wreck-NAMA_5744.jpg" },
    ],
    notes: "Museum caption: probably a copy of a bronze original by the sculptor Toinias of Sikyon.",
  },
  {
    id: "boy-2773", cat: "statuary", group: "Marble statuary",
    name: "Statue of a boy (young athlete)",
    material: "marble", matDetail: "Parian marble",
    campaign: "1900-01", date: "Early 1st c. BC",
    inv: "NAM 2773",
    imgKind: "local", imgSrc: "assets/external/marble-athlete.jpg",
    imgAlt: "Marble statue of a young athlete, well preserved on the buried right side and heavily sea-eroded on the left", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-19.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agBoy },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-19.jpeg" },
    ],
    notes: "Also used for a section-heading photograph in the museum’s own 2012 booklet — a favourite of the exhibition designers. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },
  {
    id: "horse", cat: "statuary", group: "Marble statuary",
    name: "Marble horse (one of four)",
    material: "marble", matDetail: "Marble (head and body carved from separate blocks)",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM 15536 (statue); NAM 5747 (head detail); NAM 5749 (plinth section); NAM 15554 (front hoof)",
    imgKind: "commons", imgFile: "Antikythera Marble horse.jpg",
    imgAlt: "Marble statue of a horse from the Antikythera shipwreck",
    imgStatus: "high-res",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "Wikimedia Commons file page", url: "https://commons.wikimedia.org/wiki/File:Antikythera_Marble_horse.jpg" },
    ],
    notes: "The ship carried four life-size racehorses; one was lost during the 1901 recovery operations. The head and body were made of separate blocks joined at the neck.",
  },
  {
    id: "marble-fragments", cat: "statuary", group: "Marble statuary",
    name: "Marble statue fragments (hands, limbs, drapery)",
    material: "marble", matDetail: "Marble",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM 15550, NAM 15555, NAM 15561, NAM 15562, NAM 15534",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Right hand of a male statue (15550), forearm (15555), garment fragment (15561), further hand (15562) and a fragment associated with a warrior figure (15534). Published in the 2012 exhibition booklet; more than thirty-six marble sculptures were recovered in total.",
  },

  /* ============ THE MECHANISM ============ */
  {
    id: "mechanism", cat: "mechanism", group: "The Mechanism",
    name: "The Antikythera Mechanism (main assemblage)",
    material: "bronze", matDetail: "Bronze gear trains in a wooden frame",
    campaign: "1900-01", date: "Second half of 2nd c. BC",
    inv: "NAM X 15087",
    imgKind: "commons", imgFile: "Antikythera Fragment A (Front).webp",
    imgAlt: "Front of Fragment A of the Antikythera Mechanism, showing bronze gear wheels",
    imgStatus: "high-res",
    prov: [
      { label: "ODYSSEUS (Hellenic Ministry of Culture) record", url: PROV.odysseusMechanism },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "NYU digital archive — all 82 fragments (PTM)", url: PROV.nyuAll },
      { label: "Return to Antikythera — Mechanism page", url: PROV.rtaMechanism },
    ],
    notes: "The oldest known astronomical and calendric calculator — a geared “analogue computer” with at least 30 gear wheels, dials and pointers predicting celestial movements, eclipses and a four-year athletic games cycle. 82 fragments survive (A–G and 1–75); fragments A–D were recovered in 1901, Fragment E in 1976, Fragment F was identified among stored finds in 2005, and Fragment G was separated from C during conservation cleaning.",
  },
  ...[
    ["A", "180 × 150 mm; 27 gears", "1900-01", "Recovered in 1901 with the main assemblage; the largest fragment."],
    ["B", "125 × 60 mm; 1 gear", "1900-01", "Carries the “Supplementary Inscription” on its back face."],
    ["C", "120 × 110 mm; 1 gear", "1900-01", "Includes the back-cover spiral dials (Metonic and Saros calendars)."],
    ["D", "45 × 35 mm", "1900-01", "Small fragment; imaged in the NYU archive PTM dataset."],
    ["E", "60 × 35 mm", "1976", "Recovered by the 1976 Cousteau expedition."],
    ["F", "90 × 80 mm", "1900-01", "Identified in 2005 among fragments already in museum storage."],
    ["G", "125 × 110 mm", "1900-01", "Separated from Fragment C during conservation cleaning."],
  ].map(([frag, dims, camp, note], i) => ({
    id: "frag" + frag, cat: "mechanism", group: "The Mechanism",
    name: "Fragment " + frag,
    material: "bronze", matDetail: "Bronze",
    campaign: camp, date: "Second half of 2nd c. BC",
    inv: "NAM X 15087 (fragment " + frag + ")",
    imgKind: "commons", imgFile: "Antikythera Fragment " + frag + " (Front).webp",
    imgAlt: "Front face of Fragment " + frag + " of the Antikythera Mechanism",
    imgStatus: "high-res",
    prov: [
      { label: "NYU digital archive — fragments D–G (PTM)", url: PROV.nyuDG },
      { label: "NYU digital archive — all 82 fragments", url: PROV.nyuAll },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: dims + ". " + note + " The seven fragments A–G are the mechanically significant pieces of the 82 that survive.",
  })),

  /* ============ JEWELLERY & PRECIOUS METALS ============ */
  {
    id: "earrings-1579", cat: "jewellery", group: "Gold jewellery",
    name: "Pair of gold earrings with Eros pendants",
    material: "gold", matDetail: "Gold, pearls, garnet, emeralds or prase",
    campaign: "1900-01", date: "2nd half 2nd – early 1st c. BC",
    inv: "NAM Xρ. 1579 & 1579α",
    imgKind: "local", imgSrc: "assets/external/gold-jewellery.jpg",
    imgAlt: "Gold earrings with Eros pendants, gold rings and other personal items displayed together", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-7.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-7.jpeg" },
    ],
    notes: "From a small group of gold jewellery in the cargo: three earrings with pendant cupids in all, a ring, and two settings with inlaid stones. A 2010 study (M. C. Jackson, BCH 134) re-examined this group. The exhibition photograph is a group shot showing several jewellery and personal items together. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },
  {
    id: "earring-1646", cat: "jewellery", group: "Gold jewellery",
    name: "Gold earring with kithara-playing Eros",
    material: "gold", matDetail: "Gold, pearls, garnet, emeralds or prase",
    campaign: "1900-01", date: "2nd half 2nd – early 1st c. BC",
    inv: "NAM Xρ. 1646",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agJewellery,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
    ],
    notes: "The pendant Eros plays the kithara — the “Kithara Group” discussed in the jewellery literature on the wreck.",
  },
  {
    id: "ring-1645", cat: "jewellery", group: "Gold jewellery",
    name: "Gold finger ring (man’s ring)",
    material: "gold", matDetail: "Gold",
    campaign: "1900-01", date: "2nd – 1st c. BC",
    inv: "NAM Xρ. 1645",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agJewellery,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
    ],
    notes: "Flat inner hoop, rounded outer surface, oval bezel for a now-missing semi-precious or glass-paste stone. Parallels are known from Eretria, Delos, Patras and Tarentum. A closely similar gold ring was found in the 2016 season.",
  },
  {
    id: "setting-1642", cat: "jewellery", group: "Gold jewellery",
    name: "Gold setting with inlaid stone",
    material: "gold", matDetail: "Gold with emerald or prase (ancient prasios)",
    campaign: "1900-01", date: "1st c. BC",
    inv: "NAM Xρ. 1642",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agJewellery,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
    ],
    notes: "One of two settings with inlaid stones in the gold jewellery group.",
  },
  {
    id: "bezel-1643", cat: "jewellery", group: "Gold jewellery",
    name: "Gold bezel setting",
    material: "gold", matDetail: "Hammered gold sheet with granulation",
    campaign: "1900-01", date: "2nd half 2nd – 1st c. BC",
    inv: "NAM Xρ. 1643",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agJewellery,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
    ],
    notes: "Decorated with granulation — minute gold spheres soldered to the surface.",
  },
  {
    id: "silver-bowls", cat: "jewellery", group: "Silver vessels",
    name: "Two silver calyx bowls",
    material: "silver", matDetail: "Silver, cast and soldered",
    campaign: "1900-01", date: "2nd – 1st c. BC",
    inv: "NAM Xρ. 1647, Xρ. 1648",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agJewellery,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
    ],
    notes: "Handleless bowls emulating Hellenistic ceramic tableware used for serving small portions; calyx-shaped bodies cast separately and soldered to ring bases.",
  },
  {
    id: "silver-cups", cat: "jewellery", group: "Silver vessels",
    name: "Two silver conical cups (mastoi)",
    material: "silver", matDetail: "Silver, dual-wall technique, lathe-turned and forged",
    campaign: "1900-01", date: "2nd – 1st c. BC",
    inv: "NAM Xρ. 1649, Xρ. 1650",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agJewellery,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
    ],
    notes: "Made from two superimposed, fused sheets of the same alloy but different thicknesses. Both shapes have glass counterparts in the cargo.",
  },
  {
    id: "gold-1976", cat: "jewellery", group: "Gold jewellery",
    name: "Gold jewellery (1976)",
    material: "gold", matDetail: "Gold",
    campaign: "1976", date: "Ancient (Hellenistic contexts)",
    inv: null, invNote: "Catalogue numbers not published in the consulted sources",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "Wikipedia — Antikythera wreck (1976 campaign)", url: PROV.wikiWreck },
    ],
    notes: "Gold jewellery was among the roughly 300 objects recovered by the 1976 Cousteau expedition, directed for the Ephorate by Lazaros Kolonas.",
  },
  {
    id: "gold-ring-2016", cat: "jewellery", group: "Gold jewellery",
    name: "Gold ring (2016 season)",
    material: "gold", matDetail: "Gold",
    campaign: "2015-22", date: "Ancient (Hellenistic)",
    inv: null, invNote: "Catalogue number not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.whoi2016,
    prov: [
      { label: "Woods Hole Oceanographic Institution — 2016 finds", url: PROV.whoi2016 },
    ],
    notes: "A gold ring closely resembling one recovered in 1976 was among the 60 artefacts raised in October 2016, with luxury glassware, a bronze spear and human remains.",
  },

  /* ============ CARGO — GLASS ============ */
  {
    id: "glass-23712", cat: "cargo", group: "Glass vessels",
    name: "Bowl with olive-branch relief",
    material: "glass", matDetail: "Green-blue glass, relief-cut",
    campaign: "1900-01", date: "1st half 1st c. BC",
    inv: "NAM 23712",
    imgKind: "local", imgSrc: "assets/official/glass_23712.jpg",
    imgAlt: "Green-blue glass bowl decorated with an olive branch in relief",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23712.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Of exceptional rarity: leafy olive branches shoot up from the mouth of a stylised vase. Probably mould-cast with cold cutting, or rotary-pressed. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "glass-23714", cat: "cargo", group: "Glass vessels",
    name: "Lobed bowl",
    material: "glass", matDetail: "Golden-brown glass, cast/rotary-pressed",
    campaign: "1900-01", date: "1st half 1st c. BC",
    inv: "NAM 23714",
    imgKind: "local", imgSrc: "assets/official/glass_23714.jpg",
    imgAlt: "Golden-brown glass bowl with protruding lobes and lanceolate leaf decoration",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23714.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "The largest glass vessel from the wreck: sixteen lanceolate leaves alternate with sixteen protruding lobes, with an eight-petalled rosette on the base. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "glass-23723", cat: "cargo", group: "Glass vessels",
    name: "Striped mosaic bowl",
    material: "glass", matDetail: "Polychrome mosaic glass",
    campaign: "1900-01", date: "2nd quarter 1st c. BC",
    inv: "NAM 23723",
    imgKind: "local", imgSrc: "assets/official/glass_23723.jpg",
    imgAlt: "Polychrome mosaic glass bowl with twisted and striped canes",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23723.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Mosaic-glass group: six mosaic bowls, four network-mosaic bowls and this striped mosaic bowl, made from fused cane sections sagged over a former mould — an Egyptian technique of the late 3rd–2nd c. BC. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "glass-23726", cat: "cargo", group: "Glass vessels",
    name: "Alabastron",
    material: "glass", matDetail: "Cobalt-blue glass, core-formed",
    campaign: "1900-01", date: "1st half 1st c. BC",
    inv: "NAM 23726",
    imgKind: "local", imgSrc: "assets/official/glass_23726.jpg",
    imgAlt: "Blue core-formed glass alabastron with trailed feather decoration",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23726.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "A late example of core forming — one of the oldest glassworking methods, in which the vessel is shaped around a sand-and-oxide core on a rod. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "glass-23713", cat: "cargo", group: "Glass vessels",
    name: "Conical grooved bowl",
    material: "glass", matDetail: "Colourless/coloured glass, sagged or rotary-pressed",
    campaign: "1900-01", date: "Early 1st c. BC",
    inv: "NAM 23713",
    imgKind: "local", imgSrc: "assets/official/23713.jpg",
    imgAlt: "Conical glass bowl with grooved decoration",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23713.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Drinking-vessel type associated with Syro-Palestinian production, appearing from the 2nd c. BC. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "glass-23715", cat: "cargo", group: "Glass vessels",
    name: "Fluted bowl (fragmentary)",
    material: "glass", matDetail: "Glass, rotary-pressed with cut flutes",
    campaign: "1900-01", date: "1st half 1st c. BC",
    inv: "NAM 23715",
    imgKind: "local", imgSrc: "assets/official/23715.jpg",
    imgAlt: "Fragmentary glass bowl with shallow vertical flutes",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23715.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Shallow vertical grooves cut after rotary pressing. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "glass-23718", cat: "cargo", group: "Glass vessels",
    name: "Mosaic bowl",
    material: "glass", matDetail: "Polychrome mosaic glass",
    campaign: "1900-01", date: "2nd quarter 1st c. BC",
    inv: "NAM 23718",
    imgKind: "local", imgSrc: "assets/official/23718.jpg",
    imgAlt: "Ancient mosaic glass bowl with multicoloured pattern",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23718.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "One of the six mosaic bowls in the cargo. About twenty monochrome and polychrome glass vessels in all were recovered in 1900–01, and ornate bowls again in 2016. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "glass-23709", cat: "cargo", group: "Glass vessels",
    name: "Cast bowls with tripartite handles",
    material: "glass", matDetail: "Glass, cast",
    campaign: "1900-01", date: "1st c. BC",
    inv: "NAM 23709, 23710, 23711",
    imgKind: "local", imgSrc: "assets/official/23709.jpg",
    imgAlt: "Ancient cast glass bowl",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/23709.jpg",
    prov: [
      { label: "Return to Antikythera — glassware (official project photos)", url: PROV.rtaGlass },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Three fragmentary cast bowls; one retains a tripartite handle. Official photograph by K. Xenikakis (NAM).",
  },

  /* ============ CARGO — CERAMICS & STONE ============ */
  {
    id: "amphorae", cat: "cargo", group: "Ceramics",
    name: "Transport amphorae (29)",
    material: "ceramic", matDetail: "Terracotta",
    campaign: "1900-01", date: "1st half 1st c. BC",
    inv: "Rhodes: NAM 27996, 27997, 31046; Kos: NAM 28003, 30994, 30999; Ephesos (“Nikandros Group”): NAM 30993, 30997, 30998; Adriatic (Lamboglia 2): NAM 28004",
    imgKind: "local", imgSrc: "assets/official/amphorae01.jpg",
    imgAlt: "Fragmented neck and handles of a terracotta transport amphora from the wreck",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/amphorae01.jpg",
    prov: [
      { label: "Return to Antikythera — amphorae (official project photos)", url: PROV.rtaAmphorae },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Four production origins trace the ship’s route and cargo: Rhodes and Kos (wine), Ephesos, and the Adriatic coast. Handle stamps (see the second official photo) carry manufacturer marks such as the Nikandros Group. Official photographs by K. Xenikakis (NAM); the specific amphora photographed is not individually identified.",
    extraImg: { src: "assets/official/amphorae05.jpg", alt: "Stamped amphora handle with rectangular manufacturer’s seal" },
  },
  {
    id: "lagynoi", cat: "cargo", group: "Ceramics",
    name: "Lagynoi — wine jugs (47)",
    material: "ceramic", matDetail: "Terracotta",
    campaign: "1900-01", date: "1st c. BC",
    inv: "NAM 30680–30684, 30701–30705, 30713–30715, 30718–30730, 30759–30762, 30771–30775 (partial ranges)",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "The table-wine jug par excellence of the late Hellenistic banquet. An intact lagynos was recovered again in the 2014 season.",
  },
  {
    id: "sigillata", cat: "cargo", group: "Ceramics",
    name: "Eastern Sigillata A plates and cups",
    material: "ceramic", matDetail: "Red-slipped fine ware",
    campaign: "1900-01", date: "1st half 1st c. BC",
    inv: "NAM 30624–30632, 30634–30654, 30660",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Luxurious red-slipped tableware, likely intended for the feasts of wealthy Romans — evidence the cargo was bound westward for Italian markets.",
  },
  {
    id: "megarian", cat: "cargo", group: "Ceramics",
    name: "Relief bowls, krater, jug and cooking wares",
    material: "ceramic", matDetail: "Terracotta (Megarian bowls, cooking pots, plates)",
    campaign: "1900-01", date: "1st c. BC",
    inv: "Relief bowls with inscribed rims: NAM 30708, 30709; krater: NAM 31005; jug: NAM 30967",
    imgKind: "local", imgSrc: "assets/external/relief-bowl-sherds.jpg",
    imgAlt: "Moulded relief bowl sherds with an inscribed rim and stamped rosette decoration", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-6.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agPottery },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-6.jpeg" },
    ],
    notes: "Megarian (relief) bowls carry inscriptions naming their owners; cooking pots with traces of burning and plain plates point to food preparation aboard during the voyage. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },
  {
    id: "lamps", cat: "cargo", group: "Ceramics",
    name: "Oil lamps (nine)",
    material: "ceramic", matDetail: "Terracotta",
    campaign: "1900-01", date: "1st c. BC",
    inv: "NAM 30620 (with burning traces); official project photos also catalogue NAM 30615–30619, 30957",
    imgKind: "local", imgSrc: "assets/official/30615.jpg",
    imgAlt: "Clay oil lamp with looped handle and nozzle from the wreck",
    imgStatus: "high-res",
    imgLink: "https://antikythera.org.gr/wp-content/uploads/2014/04/30615.jpg",
    prov: [
      { label: "Return to Antikythera — lamps (official project photos)", url: PROV.rtaLamps },
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Nine lamps were recovered, at least one showing clear use for lighting on board. Official photograph by K. Xenikakis (NAM).",
  },
  {
    id: "filter-jugs", cat: "cargo", group: "Ceramics",
    name: "Filter jugs (two)",
    material: "ceramic", matDetail: "Terracotta",
    campaign: "1900-01", date: "1st c. BC",
    inv: "NAM 30769, 30770",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Spouted jugs with strainers, likely used to fill lamps with oil.",
  },
  {
    id: "quern", cat: "cargo", group: "Stone utensils",
    name: "Rotary quern (hand-mill)",
    material: "stone", matDetail: "Stone (pair of millstones)",
    campaign: "1900-01", date: "Early 1st c. BC",
    inv: "NAM 15556, 15563",
    imgKind: "local", imgSrc: "assets/external/quern-mortarium.jpg",
    imgAlt: "Rotary quern hand-mill and stone mortar displayed with ceramic vessels", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-5.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-5.jpeg" },
    ],
    notes: "A manually operated quern for grinding grain — with the cooking pots, evidence that food was prepared on board. The exhibition photograph also shows the mortarium and ceramic vessels. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },
  {
    id: "grindstone-mortarium", cat: "cargo", group: "Stone utensils",
    name: "Grindstone and mortarium",
    material: "stone", matDetail: "Stone",
    campaign: "1900-01", date: "2nd – 1st c. BC",
    inv: "Finger-shaped grindstone: NAM 31055; mortarium (shallow basin): NAM 15557",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Kitchen equipment: a grindstone in the shape of a finger, and a mortar-type basin unchanged in shape from the Archaic period to the Roman imperial era.",
  },

  /* ============ CARGO — METAL VESSELS & COINS ============ */
  {
    id: "jug-18937", cat: "cargo", group: "Metal vessels",
    name: "Biconical bronze jug (prochous)",
    material: "bronze", matDetail: "Bronze, hammered",
    campaign: "1900-01", date: "Late 2nd – early 1st c. BC",
    inv: "NAM X 18937",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agBronzeVessels,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agBronzeVessels },
    ],
    notes: "A type widespread in Italy in the 2nd–1st c. BC; two more specimens are recognisable in the wreck from their handles, which have parallels on Delos.",
  },
  {
    id: "kados", cat: "cargo", group: "Metal vessels",
    name: "Bronze bucket (kados) parts",
    material: "bronze", matDetail: "Bronze with dotted floral decoration",
    campaign: "1900-01", date: "Late 2nd – early 1st c. BC",
    inv: "NAM X 18939α–γ (rim and handle fittings; further fittings X 18940γ)",
    imgKind: "local", imgSrc: "assets/external/bronze-vessel-parts.jpg",
    imgAlt: "Corroded bronze and tin vessels and fittings: a jug, miniature oinochoai, handles and mounts", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-8.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agBronzeVessels },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-8.jpeg" },
    ],
    notes: "The rim’s dotted floral decoration points to Campanian workshops; a rectangular frame is probably a manufacturer’s stamp. The exhibition photograph is a group shot of bronze and tin vessel parts, including miniature tin vessels. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },
  {
    id: "tin-vessels", cat: "cargo", group: "Metal vessels",
    name: "Miniature tin vessels",
    material: "lead", matDetail: "Tin (miniature oinochoai, lamp, kyathos)",
    campaign: "1900-01", date: "2nd – 1st c. BC",
    inv: "NAM X 15109α–β, X 18938, X 18978",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agBronzeVessels,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agBronzeVessels },
    ],
    notes: "Tin vases are generally scarce; a shell among the metal finds may have covered a lamp’s fill-hole.",
  },
  {
    id: "lead-pyxis", cat: "cargo", group: "Metal vessels",
    name: "Lead pyxis",
    material: "lead", matDetail: "Lead (lid missing)",
    campaign: "1900-01", date: "Late 2nd – early 1st c. BC",
    inv: "NAM X 26786",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agJewellery,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agJewellery },
    ],
    notes: "The single lead vessel in the finds.",
  },
  {
    id: "cistophoroi", cat: "cargo", group: "Coins",
    name: "Silver cistophoric tetradrachms (36)",
    material: "silver", matDetail: "Silver",
    campaign: "1900-01", date: "Issues down to 85–76 BC",
    inv: "32 Pergamon, 4 Ephesos; illustrated specimen: Numismatic Museum, Athens, ΒΠ 707: 19.024/2",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "The latest coins date the shipwreck to shortly after 70–60 BC. Some specimens are held by the Numismatic Museum, Athens.",
  },
  {
    id: "bronze-coins", cat: "cargo", group: "Coins",
    name: "Bronze coins (48)",
    material: "bronze", matDetail: "Bronze",
    campaign: "1900-01", date: "3rd – 1st c. BC",
    inv: null, invNote: "Individual numbers not published in the consulted sources",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Includes three Sicilian issues (187–170 BC) — hinting at a transaction on Italian soil — and three Asia Minor issues (250–210 BC and 70–60 BC).",
  },

  /* ============ SHIP’S EQUIPMENT ============ */
  {
    id: "lead-sheathing", cat: "cargo", group: "Ship’s equipment",
    name: "Lead hull sheathing",
    material: "lead", matDetail: "Lead sheets with bronze fastenings",
    campaign: "1900-01", date: "Hull dated 220 BC (± 43)",
    inv: "NAM X 19015",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agHull,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agHull },
    ],
    notes: "The hull’s wooden planks were sheathed in lead to deter shipworm — a practice for long-haul routes. Hull timbers recovered in 1976 were of elm; further planks came up in 2014.",
  },
  {
    id: "water-pipe", cat: "cargo", group: "Ship’s equipment",
    name: "Lead water pipe (scupper)",
    material: "lead", matDetail: "Lead",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM X 19014",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agShipParts,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agShipParts },
    ],
    notes: "Part of the ship’s drainage system.",
  },
  {
    id: "sounding-weights", cat: "cargo", group: "Ship’s equipment",
    name: "Sounding weights (6 kg and 14 kg)",
    material: "lead", matDetail: "Lead",
    campaign: "1900-01", date: "First half 1st c. BC",
    inv: "NAM X 19012, X 19013",
    imgKind: "local", imgSrc: "assets/external/sounding-weights.jpg",
    imgAlt: "Two bell-shaped lead sounding weights with lead pipe, rigging rings and lead weights", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-2.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agShipParts },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-2.jpeg" },
    ],
    notes: "Leads used to sound the depth of the sea (katapeirateriai); the two weights suggest both sounding and possibly anchoring functions. The exhibition photograph also shows the lead scupper pipe, bronze rings and lead weights. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },
  {
    id: "lead-weights", cat: "cargo", group: "Ship’s equipment",
    name: "Lead weights",
    material: "lead", matDetail: "Lead",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM X 26783–26785",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Balance or fishing weights from the ship’s gear.",
  },
  {
    id: "bronze-nails", cat: "cargo", group: "Ship’s equipment",
    name: "Bronze nails and spikes",
    material: "bronze", matDetail: "Bronze",
    campaign: "1900-01", date: "Hellenistic",
    inv: "NAM X 19007γ (with further examples)",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.agHull,
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agHull },
    ],
    notes: "Fastenings from the hull and fittings.",
  },
  {
    id: "roof-tiles", cat: "cargo", group: "Ship’s equipment",
    name: "Corinthian roof tiles",
    material: "ceramic", matDetail: "Terracotta (flat and cover tiles)",
    campaign: "1900-01", date: "First half 1st c. BC",
    inv: "NAM 30878, 30889",
    imgKind: "local", imgSrc: "assets/external/roof-tiles.jpg",
    imgAlt: "Corinthian pan and cover roof tiles from the ship's sheltered deck structure", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-3.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agTiles },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-3.jpeg" },
    ],
    notes: "The tiles roofed a sheltered living area of the ship. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },
  {
    id: "klinai", cat: "cargo", group: "Ship’s equipment",
    name: "Luxury couches (klinai) — fittings",
    material: "bronze", matDetail: "Bronze revetments on wooden frames",
    campaign: "1900-01", date: "150–100 BC",
    inv: "Fulcrum with female bust: NAM X 15099; lion’s-head headrest: NAM X 15098; bird finial: NAM 15101; leg bases: NAM X 18922–18924; side rails: NAM X 18925, X 18929, X 18968",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
    ],
    notes: "Elaborately decorated bronze fittings from at least two couches, assembled before loading — luxury furniture among the cargo. An ornate bronze bed leg was recovered again in the 2014 season.",
  },
  {
    id: "hull-plank-2011", cat: "cargo", group: "Ship’s equipment",
    name: "Hull plank fragment",
    material: "wood", matDetail: "Wood (with lead sheeting traces)",
    campaign: "1900-01", date: "220 BC (± 43)",
    inv: "Ephorate of Underwater Antiquities ΒΕ 2011/11",
    imgKind: "local", imgSrc: "assets/external/hull-plank.jpg",
    imgAlt: "Preserved wooden hull timber with lead sheeting and bronze spikes, 220 BC (± 43)", imgStatus: "high-res",
    imgLink: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-1.jpeg",
    prov: [
      { label: "NAM exhibition booklet (2012)", url: PROV.booklet },
      { label: "2013 NAM exhibition photographs (ancient-greece.org)", url: PROV.agHull },
      { label: "Image source — ancient-greece.org (CC BY-NC-ND 4.0)", url: "https://ancient-greece.org/wp-content/uploads/Antikythera-Shipwreck-1.jpeg" },
    ],
    notes: "Held by the Ephorate of Underwater Antiquities under its own inventory series (ΒΕ), separate from the NAM catalogue. The exhibition photograph also shows lead sheathing sheets and bronze spikes. Photograph: ancient-greece.org, CC BY-NC-ND 4.0."
  },

  /* ============ 1976 EXPEDITION ============ */
  {
    id: "hull-planks-1976", cat: "cargo", group: "1976 expedition",
    name: "Hull planks of elm (four)",
    material: "wood", matDetail: "Elm with lead sheathing",
    campaign: "1976", date: "Ancient hull, 220 BC (± 43)",
    inv: null, invNote: "Catalogue numbers not published in the consulted sources",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "Wikipedia — Antikythera wreck (1976 campaign)", url: PROV.wikiWreck },
    ],
    notes: "The 1976 Jacques-Yves Cousteau expedition with Calypso recovered roughly 300 objects, directed for the Greek Ephorate of Underwater Antiquities by Lazaros Kolonas.",
  },
  {
    id: "coins-1976", cat: "cargo", group: "1976 expedition",
    name: "Bronze and silver coins (1976)",
    material: "bronze", matDetail: "Bronze and silver",
    campaign: "1976", date: "Hellenistic issues",
    inv: null, invNote: "Catalogue numbers not published in the consulted sources",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "Wikipedia — Antikythera wreck (1976 campaign)", url: PROV.wikiWreck },
    ],
    notes: "Coins raised by Cousteau’s team alongside sculpture fragments and small bronze statuettes.",
  },
  {
    id: "remains-1976", cat: "cargo", group: "1976 expedition",
    name: "Human remains (1976)",
    material: "organic", matDetail: "Human skeletal remains",
    campaign: "1976", date: "Ancient",
    inv: null, invNote: "Catalogue numbers not published in the consulted sources",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "Wikipedia — Antikythera wreck (1976 campaign)", url: PROV.wikiWreck },
    ],
    notes: "The first evidence of the people on board; further remains were recovered in 2016.",
  },

  /* ============ 2012–14 — RETURN TO ANTIKYTHERA ============ */
  {
    id: "anchors-2014", cat: "cargo", group: "Return to Antikythera (2012–14)",
    name: "Two lead anchor assemblages",
    material: "lead", matDetail: "Lead (stocks and parts over 1 m)",
    campaign: "2012-14", date: "Ancient (1st c. BC)",
    inv: null, invNote: "Held by the Ephorate of Underwater Antiquities; numbers not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.sciNews2014,
    prov: [
      { label: "sci.news — 2014 season report", url: PROV.sciNews2014 },
      { label: "Wikipedia — Antikythera wreck (2014 season)", url: PROV.wikiWreck },
    ],
    notes: "Recovered 15 September – 7 October 2014, with hull planks, intact ceramics and a bronze spear, during the first systematic excavation of the wreck since 1976.",
  },
  {
    id: "rigging-ring-2014", cat: "cargo", group: "Return to Antikythera (2012–14)",
    name: "Bronze rigging ring (with wood)",
    material: "bronze", matDetail: "Bronze with preserved wood",
    campaign: "2012-14", date: "Ancient (1st c. BC)",
    inv: null, invNote: "Held by the Ephorate of Underwater Antiquities; number not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.sciNews2014,
    prov: [
      { label: "sci.news — 2014 season report", url: PROV.sciNews2014 },
    ],
    notes: "From the ship’s rigging, with wood preserved inside the ring — evidence of the ship’s sailing gear.",
  },
  {
    id: "hull-2014", cat: "cargo", group: "Return to Antikythera (2012–14)",
    name: "Hull planks (2014)",
    material: "wood", matDetail: "Wood",
    campaign: "2012-14", date: "Ancient hull",
    inv: null, invNote: "Held by the Ephorate of Underwater Antiquities; number not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.sciNews2014,
    prov: [
      { label: "sci.news — 2014 season report", url: PROV.sciNews2014 },
    ],
    notes: "Ship’s timbers mapped and recovered during the 2014 season.",
  },
  {
    id: "lagynos-2014", cat: "cargo", group: "Return to Antikythera (2012–14)",
    name: "Intact lagynos (table jug)",
    material: "ceramic", matDetail: "Terracotta",
    campaign: "2012-14", date: "Ancient (1st c. BC)",
    inv: null, invNote: "Held by the Ephorate of Underwater Antiquities; number not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.sciNews2014,
    prov: [
      { label: "sci.news — 2014 season report", url: PROV.sciNews2014 },
    ],
    notes: "An intact table jug recovered in 2014, displayed in the 2014 exhibition of the season’s finds.",
  },
  {
    id: "kline-leg-2014", cat: "cargo", group: "Return to Antikythera (2012–14)",
    name: "Ornate bronze bed (kline) leg",
    material: "bronze", matDetail: "Bronze",
    campaign: "2012-14", date: "Ancient (1st c. BC)",
    inv: null, invNote: "Held by the Ephorate of Underwater Antiquities; number not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.sciNews2014,
    prov: [
      { label: "sci.news — 2014 season report", url: PROV.sciNews2014 },
    ],
    notes: "A richly ornamented leg from a couch of the same luxury type as the 1900–01 kline fittings.",
  },
  {
    id: "spear-2014", cat: "cargo", group: "Return to Antikythera (2012–14)",
    name: "Bronze spear (about 2 m)",
    material: "bronze", matDetail: "Bronze",
    campaign: "2012-14", date: "Ancient (1st c. BC)",
    inv: null, invNote: "Held by the Ephorate of Underwater Antiquities; number not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.sciNews2014,
    prov: [
      { label: "sci.news — 2014 season report", url: PROV.sciNews2014 },
      { label: "Wikipedia — Antikythera wreck (2014 season)", url: PROV.wikiWreck },
    ],
    notes: "A two-metre spear — likely once attached to a life-size warrior statue, echoing the statue spears of the original cargo. A second bronze spear was recovered in 2016.",
  },

  /* ============ 2015–22 — LATER SEASONS ============ */
  {
    id: "finds-2016", cat: "cargo", group: "Later seasons (2015–22)",
    name: "2016 season finds (60 artefacts)",
    material: "mixed", matDetail: "Gold, glass, bronze, marble, ceramics, lead",
    campaign: "2015-22", date: "Ancient",
    inv: null, invNote: "Individual catalogue numbers not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.whoi2016,
    prov: [
      { label: "Woods Hole Oceanographic Institution — October 2016 release", url: PROV.whoi2016 },
      { label: "Wikipedia — Antikythera wreck (2014–16 seasons)", url: PROV.wikiWreck },
    ],
    notes: "Luxury glassware, gold jewellery, a bronze spear from a statue, marble sculpture elements, incense or resin, ceramic decanters and a defensive weapon of nearly 100 kg of lead — a “dolphin”, the only one ever found in archaeological context. Recovered with WHOI rebreather divers, 2016.",
  },
  {
    id: "skeleton-2016", cat: "cargo", group: "Later seasons (2015–22)",
    name: "Human skeleton (“Pamphilos”)",
    material: "organic", matDetail: "Human skeletal remains",
    campaign: "2015-22", date: "Ancient",
    inv: null, invNote: "Individual catalogue number not yet published",
    imgKind: null, imgAlt: "", imgStatus: "none",
    prov: [
      { label: "Wikipedia — Antikythera wreck (2016 season)", url: PROV.wikiWreck },
    ],
    notes: "Recovered on 31 August 2016 — at least one individual who went down with the ship, informally nicknamed “Pamphilos” in reports of the excavation.",
  },
  {
    id: "finds-2017", cat: "cargo", group: "Later seasons (2015–22)",
    name: "2017 season finds",
    material: "mixed", matDetail: "Bronze arm, marble leg, gold ring, bronze disc",
    campaign: "2015-22", date: "Ancient",
    inv: null, invNote: "Individual catalogue numbers not yet published",
    imgKind: null, imgAlt: "", imgStatus: "photo at source",
    imgLink: PROV.rta2017,
    prov: [
      { label: "Return to Antikythera — official press release, 4 October 2017", url: PROV.rta2017 },
    ],
    notes: "A bronze arm, a marble leg, a gold ring and a bronze object decorated with a bull, recovered in the October 2017 season.",
  },
];

const CATEGORIES = [
  { id: "statuary", label: "Statuary", blurb: "Bronze and marble sculpture recovered from the wreck — from the life-size Youth and the Cynic Philosopher to monumental marbles of Zeus and Heracles. More than thirty-six marble statues and numerous bronze fragments were raised in 1900–01; a 2025 study suggests the assemblage may derive from a single gymnasion." },
  { id: "mechanism", label: "The Mechanism", blurb: "The Antikythera Mechanism (NAM X 15087): 82 surviving fragments of the world’s oldest known astronomical calculator, built in the second half of the 2nd century BC. Fragments A–D came up in 1901; E in 1976; F was identified in museum storage in 2005; G was separated from C during cleaning." },
  { id: "jewellery", label: "Jewellery & precious metals", blurb: "A small but exquisite group: gold earrings with Eros pendants, a man’s gold ring, inlaid settings, and silver table vessels — the personal luxury goods in the cargo." },
  { id: "cargo", label: "Cargo & ship’s equipment", blurb: "The commercial cargo and the ship itself: glass bowls, ceramics, stone utensils, bronze and tin vessels, coins, couch fittings, hull timbers, anchors and rigging — spanning the 1900–01 salvage, the 1976 Cousteau expedition and the Return to Antikythera seasons from 2012." },
];

const CAMPAIGN_LABELS = {
  "1900-01": "1900–01",
  "1976": "1976",
  "2012-14": "2012–14",
  "2015-22": "2015–22",
};

const MATERIAL_LABELS = {
  "bronze": "Bronze", "marble": "Marble", "glass": "Glass", "ceramic": "Ceramic",
  "gold": "Gold", "silver": "Silver", "lead": "Lead & tin", "stone": "Stone",
  "wood": "Wood", "organic": "Organic", "mixed": "Mixed",
};
